stages:
  - lint
  - build
  - release

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  MAIN_IMAGE_TAG: $CI_REGISTRY_IMAGE:main
  RELEASE_IMAGE_TAG: $CI_REGISTRY_IMAGE:release

lint:
  image: node:12
  stage: lint
  script:
    - yarn --frozen-lockfile
    - yarn locales:compile
    - yarn lint

build:
  image: docker.io/docker:stable
  stage: build
  tags:
    - medium
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg COMMIT=$CI_COMMIT_SHA --build-arg MAPTILER_STYLE_KEY=$MAPTILER_STYLE_KEY --build-arg VECTOR_TILE_URL=$VECTOR_TILE_URL -t $MAIN_IMAGE_TAG .
    - docker push $MAIN_IMAGE_TAG
  only:
    - main

release:
  image: docker.io/docker:stable
  stage: release
  tags:
    - medium
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg COMMIT=$CI_COMMIT_SHA -t $RELEASE_IMAGE_TAG -t $CI_REGISTRY_IMAGE:$(./scripts/get-package-version.sh) .
    - docker push $RELEASE_IMAGE_TAG
    - docker push $CI_REGISTRY_IMAGE:$(./scripts/get-package-version.sh)
  only:
    - /^v\d+\.\d+\.\d+$/ # use `yarn version` to create these tags
  except:
    - branches
