blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/visualize-admin/visualization-tool/discussions
    about: Open a discussion to ask general questions and get help with using the Visualization Tool
