name: Basic checks (lint, typecheck, unit tests)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  basic-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"
      - run: yarn install --immutable --prefer-offline
      - run: yarn lint
      - run: yarn typecheck
      - run: yarn test
