name: Manual Load Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to test"
        required: true
        default: int
        type: choice
        options:
          - test
          - int
          - prod
      gql-server-side-cache:
        description: "Enable GraphQL server-side cache"
        required: true
        default: true
        type: boolean

env:
  ENV: ${{ inputs.environment }}
  ENABLE_GQL_SERVER_SIDE_CACHE: ${{ inputs.gql-server-side-cache }}

jobs:
  k6:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Testing GraphQL - Components
        if: always()
        uses: grafana/k6-action@v0.2.0
        with:
          filename: k6/graphql/components.js
          cloud: true
          token: ${{ secrets.K6_CLOUD_API_TOKEN }}
          flags: --env ENV=${{ env.ENV }} --env ENABLE_GQL_SERVER_SIDE_CACHE=${{ env.ENABLE_GQL_SERVER_SIDE_CACHE }}

      - name: Testing GraphQL - Observations
        if: always()
        uses: grafana/k6-action@v0.2.0
        with:
          filename: k6/graphql/observations.js
          cloud: true
          token: ${{ secrets.K6_CLOUD_API_TOKEN }}
          flags: --env ENV=${{ env.ENV }} --env ENABLE_GQL_SERVER_SIDE_CACHE=${{ env.ENABLE_GQL_SERVER_SIDE_CACHE }}

      - name: Testing HAR - Edition
        if: always()
        uses: grafana/k6-action@v0.2.0
        with:
          filename: k6/har/${{ env.ENV }}/edition.js
          cloud: true
          token: ${{ secrets.K6_CLOUD_API_TOKEN }} --env ENABLE_GQL_SERVER_SIDE_CACHE=${{ env.ENABLE_GQL_SERVER_SIDE_CACHE }}
