name: Performance tests

on: workflow_dispatch

jobs:
  compile:
    name: Compile site assets
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: grafana/k6:latest
          options: -v ${{ github.workspace }}:/root -e K6_PROMETHEUS_RW_USERNAME=${{ secrets.K6_PROMETHEUS_RW_USERNAME }} -e K6_PROMETHEUS_RW_PASSWORD=${{ secrets.K6_PROMETHEUS_RW_PASSWORD }} -e K6_PROMETHEUS_RW_SERVER_URL=${{ secrets.K6_PROMETHEUS_RW_SERVER_URL }}
          run: k6 run -o experimental-prometheus-rw --tag testid=DataCubeMetadata --env ENV=test --env CUBE_IRI=https://culture.ld.admin.ch/sfa/StateAccounts_Office/4/ --env CUBE_LABEL=StateAccounts_Office/4/ - </root/k6/performance-tests/graphql/DataCubeMetadata.js && k6 run -o experimental-prometheus-rw --tag testid=DataCubeMetadata --env ENV=int --env CUBE_IRI=https://culture.ld.admin.ch/sfa/StateAccounts_Office/4/ --env CUBE_LABEL=StateAccounts_Office/4/ - </root/k6/performance-tests/graphql/DataCubeMetadata.js && k6 run -o experimental-prometheus-rw --tag testid=DataCubeMetadata --env ENV=prod --env CUBE_IRI=https://culture.ld.admin.ch/sfa/StateAccounts_Office/4/ --env CUBE_LABEL=StateAccounts_Office/4/ - </root/k6/performance-tests/graphql/DataCubeMetadata.js